// Mirror of core/src/Brawlers.cpp so every edition plays the same characters.
// All names and stats are original to Mega Stars.

export const ROSTER = [
  {
    id: 'faisca',
    displayName: 'Faísca',
    attack: 'single',
    maxHealth: 3600,
    moveSpeed: 4.4,
    attackRange: 8.0,
    reloadSeconds: 0.9,
    ammoCapacity: 3,
    projectilesPerShot: 1,
    spreadDegrees: 0,
    damagePerProjectile: 1100,
    projectileSpeed: 13.0,
    superChargePerHit: 12,
    color: '#f2c14e',
    blurb: 'Equilibrada: tiro reto de longo alcance.',
  },
  {
    id: 'bruto',
    displayName: 'Bruto',
    attack: 'spread',
    maxHealth: 5600,
    moveSpeed: 4.0,
    attackRange: 4.5,
    reloadSeconds: 1.4,
    ammoCapacity: 3,
    projectilesPerShot: 5,
    spreadDegrees: 34,
    damagePerProjectile: 420,
    projectileSpeed: 11.0,
    superChargePerHit: 8,
    color: '#e2574c',
    blurb: 'Tanque de curta distância com leque de projéteis.',
  },
  {
    id: 'estopim',
    displayName: 'Estopim',
    attack: 'lobbed',
    maxHealth: 3800,
    moveSpeed: 4.2,
    attackRange: 6.5,
    reloadSeconds: 1.1,
    ammoCapacity: 3,
    projectilesPerShot: 1,
    spreadDegrees: 0,
    damagePerProjectile: 1500,
    projectileSpeed: 9.0,
    superChargePerHit: 20,
    color: '#8e6bd6',
    blurb: 'Arremessa bombas por cima das paredes.',
  },
  {
    id: 'rajada',
    displayName: 'Rajada',
    attack: 'burst',
    maxHealth: 3200,
    moveSpeed: 5.0,
    attackRange: 6.0,
    reloadSeconds: 0.7,
    ammoCapacity: 4,
    projectilesPerShot: 3,
    spreadDegrees: 10,
    damagePerProjectile: 420,
    projectileSpeed: 15.0,
    superChargePerHit: 9,
    color: '#4ecd8f',
    blurb: 'Rápida, dispara rajadas curtas.',
  },
  {
    id: 'mira',
    displayName: 'Mira',
    attack: 'beam',
    maxHealth: 2600,
    moveSpeed: 4.1,
    attackRange: 12.0,
    reloadSeconds: 1.8,
    ammoCapacity: 3,
    projectilesPerShot: 1,
    spreadDegrees: 0,
    damagePerProjectile: 1800,
    projectileSpeed: 20.0,
    superChargePerHit: 25,
    color: '#4fa8e8',
    blurb: 'Franco-atiradora: dano alto, recarga lenta.',
  },
  {
    id: 'pilha',
    displayName: 'Pilha',
    attack: 'healing',
    maxHealth: 3400,
    moveSpeed: 4.3,
    attackRange: 7.0,
    reloadSeconds: 1.0,
    ammoCapacity: 3,
    projectilesPerShot: 1,
    spreadDegrees: 0,
    damagePerProjectile: 900,
    projectileSpeed: 12.0,
    superChargePerHit: 15,
    color: '#f08bc8',
    blurb: 'Suporte: seus tiros curam aliados.',
  },
];

export function findBrawler(id) {
  return ROSTER.find((b) => b.id === id) || ROSTER[0];
}
